# Generated by Django 5.0.7 on 2024-07-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_newsletter_delete_newslatter'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=12)),
                ('gmail', models.EmailField(max_length=30)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
