# Generated by Django 5.0.7 on 2024-07-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_contact_gmail_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('position_applied_for', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
