# Generated by Django 5.0.7 on 2024-07-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
