# Generated by Django 5.0.7 on 2024-07-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_spaceimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.AlterField(
            model_name='spaceimg',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
