# Generated by Django 5.0.7 on 2024-07-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_emsimg_alter_spaceimg_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emsimg',
            name='etitle',
        ),
        migrations.RemoveField(
            model_name='spaceimg',
            name='title',
        ),
    ]
