# Generated by Django 5.0.7 on 2024-08-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_emsimg_etitle_remove_spaceimg_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcvImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
