# Generated by Django 5.0.7 on 2024-08-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_acvimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
    ]
